deploy:
  true:
    condition: $TOXENV == py27
    repo: mwilliammyers/sportsstats
    tags: true
  password:
    secure: !!binary |
      RXZQbjRUN1FvNklXTVBFYXlPSjZBRm9jbE4zMU1qQkhDU01vN2dSWVZFdGNSVklmTWN6aGR5TDk3
      bEh5ZVZ5VzdUaWwra1NYd085RGdkWlAvb1NEUkd4aEJVWkZXL0JCUGdFTXppSW9vYzVlbHNhaWg3
      MVU3SXRLNWQ1bHlOcTVYV3I1SU54U0tIL1VXSTZuMzVOKzl6R2E5ZlVxcnlsOE51ZUJGV1FiRTV0
      NDNQUzJLSk1sN0diUnRQZGgyUm5xeTMySDluTG5xYitQa1hnMitTN3laVWRnL2xOWTEyV002a21M
      Tm5nbVpUTmI3T0hBR0o2NlViWGRhNnJKNUphdWNpNUVid3JTZ0xHaHQ4cjhEOUpBTzR4ckxVdGIx
      THRJUkpxQ2V2dHFjOC93SkMzaWJIOGVMOGNsUWsxT01uWDN3WnhBM2tpbk9XVzNaWWlhc2dJdFRG
      NTJRTElmcE1kellEWWpZcjdwVm40cThBUktWSktuQVptMVYzaS9NWmlURnd3UmNEcUtuK1h4Mjdw
      ZzRKTEJUN3dlZFBvcW02RllNYWFlREJ2bDFTRXBZejNhUGhIV0RoUG5kQnZYNEhjc1YvNkpsdzdL
      Z3BxWktReGJlVkg5QjFLSGovWHVlTnFCWnR1ckhiZFB1aGtFTmJHUlNsaWk5MHFZT25VVVlOMElV
      WTRtSU1pcEFGeUdkVUluVXJ2SFZCUEFMTVJqbVAxWUd5ViswbXh0Y0F0bHBZdzJSMkFaMkxieElX
      MVVVc0tqSHMwSVkwRVJxV0FlY01JdXBoUCtOMmFFUGE3azFsZlJSSXp4b3FCMDhKajYvODhWT1dh
      ekZlcGFXbjB6VVZNdHBPOVVOTDNpVjZTVno0Q3h6bFkwMjNHWDMwc2dYQzNkSnh1WWR6L3ZSczA9
  distributions: sdist bdist_wheel
  provider: pypi
  user: mwilliammyers
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=pypy
install: 
  - pip install -U tox flake8
language: python
python: 3.5
script:
  - make lint
  - make test-all
