deploy:
  provider: pypi
  user: mwilliammyers
  password:
    secure: zSk4jf4vaTI9gIBWjguVhf+fRkQP/hQaOQERqZJVKo+9VlRm6xtgth0GvWhdksTl1/4C2qfbWu31uIQ7rswZxBZEgBogDGk8uCFsaD+G9mV3cp2XiH2C2+G8FCMXbMbPmBD3vOujik+2gROSq5o5ky+YEJ5eRoRxRF0Hk0GpTFMWSFqZkn+jeBjv2ZBVXQSTSoIEEe1KIfOEX802amEdBukeP0EbCmtREhonvxANwjnGgQ77yHcKENPhosT/UhS/x8h1sKT189TMcd33aE5nykTn8gbbZ2XC6hk4zoALsEN5p/i10rtvZ4TeRss+X3No5eeXTTpERQM5dJ2vCLkdhPLTyqeA/HG4W1KR7idlurAWI5cSYyUgwWpolJw646svz/kyTIzGDrVJV6x/uA7N+a8Wqe0wmtlumVFe+s5yjuXZOFxspi63k13LcoQnV9cGs26Sja0RFS8XxcHA/zQW7ZqqOVR87VGcwuMJR3E7EfQQq9wUwz5tge9DOznpvwF+vMJpX0s1FQ0B6NlMXpd+4HQ5tmnlM2eN4c8PPE5Fnpj9s15nddcEcltBmvYqcE8JeZNJzowt9zX3KL/GJF6vkXK172A4eckG0JUXiyGOo56OefJ+m8z0Do5fVV0Yhec2VBjlexlAVV37O7UvSOnX+2lU9NASxphSe3nMlt6iD14=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mwilliammyers/sportsstats
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=pypy
install:
- pip install -U tox flake8
language: python
python: 3.5
script:
- make lint
- make test-all
